### ISSUE TITLE
New lines are not respected in html

### ISSUE THREAD

**Issue by zxiiro** [Jakski/sphinxcontrib-autoyaml#1]
This is an interesting project and we would love to use this to generate docs from my YAML files. Unfortunately one issue we found is that when generating html output it does not produce the correct html to respect newlines. This causes the auto-generated code to appear all as a single line of code when generating html output.

**Comment by Jakski** [comment]
@zxiiro Thank you for feedback. Does problem occur in latest version 0.3.3? If so, can you provide example problematic YAML code?

**Comment by Jakski** [comment]
Closing due to long inactivity. This issue might has been solved in https://github.com/Jakski/sphinxcontrib-autoyaml/commit/1dcf8d3d5aae4969dcdbce3d717110cac4be9538
