### ISSUE TITLE
Support for Sphinx > 4.0.0

### ISSUE THREAD

**Issue by kakila** [Jakski/sphinxcontrib-autoyaml#12]
Sphinx older than 4.5 have a problem with newest jinja: https://github.com/sphinx-doc/sphinx/issues/10306
When will autoyaml support Sphinx > 4.0.0?

**Comment by Jakski** [comment]
Support for newer Sphinx versions has been added in release [0.6.2](https://pypi.org/project/sphinxcontrib-autoyaml/0.6.2/). Thank you for pointing this out.
