### ISSUE TITLE
Support Sphinx > 6.0.0

### ISSUE THREAD

**Issue by kakila** [Jakski/sphinxcontrib-autoyaml#14]
Hi,
Thank you por the package!
Is there a reason to hold Sphinx below 6?

**Comment by Jakski** [comment]
Sphinx is limited to major versions as covered by tests. I've experimentally run tests with version 6.x and there seem to be no issues, but Poetry won't let build package satisfying Sphinx `^6` requirement, while maintaining supported Python version range in package. Precisely it gives:

```
The current project's Python requirement (>=3.6,<4.0) is not compatible with some of the required packages Python requirement:
  - sphinx requires Python >=3.8, so it will not be satisfied for Python >=3.6,<3.8
```

with Python 3.9, while trying to build package supporting Python `^3.6` https://github.com/Jakski/sphinxcontrib-autoyaml/blob/91840f4ca01e3d46dec25267f107adfe78c64be9/pyproject.toml#L21

I've added release [1.1.0](https://pypi.org/project/sphinxcontrib-autoyaml/1.1.0/) with relaxed Sphinx version requirements, but without automated tests performed by GitHub Actions for `Sphinx@^6`.

Let me know, if you have some better solution to this problem. `sphinxcontrib-autoyaml` should work well with `Sphinx@^6`, but problem with dependency resolution prevents me from testing with wider Python version support.

Python 3.6 and 3.7 will be [no longer supported by June](https://devguide.python.org/versions/), so even without resolving this problem, we should be safe to lift Python requirements to `^3.8`, thus satisfying Sphinx `^6` in the few months.

**Comment by Jakski** [comment]
Added tests for Sphinx 6 and 7 in version 1.1.3.

Also migrated from Poetry to setuptools to keep CI scripts simpler.
