### ISSUE TITLE
autoyaml_root seems to be ignored

### ISSUE THREAD

**Issue by spellancer** [Jakski/sphinxcontrib-autoyaml#2]
Hi! 

I'm getting this traceback: 

```
Exception occurred:
  File "../lib/python2.7/site-packages/sphinxcontrib/autoyaml/__init__.py", line 31, in run
    self.arguments[0]
AutoYAMLException: splunk.rst:28: location "splunk.connection.yaml" is not a file.
The full traceback has been saved in /var/folders/fy/j7m4wtws7110sjz28y9twsvxvt4yhl/T/sphinx-err-f2zpyX.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Dir structure: 
```
.
├── docs
│   └── source
│       ├── conf.py
│       └── splunk.rst
└── splunk
    └── connection.yaml
```

In **conf.py**, before extensions load:
`autoyaml_root = "../../"`

Tried few options: 
```
.. autoyaml:: splunk.connection.yaml
# OR 
.. autoyaml:: splunk/connection.yaml
# OR 
.. autoyaml:: connection.yaml
# OR 
.. autoyaml:: ../../splunk/connection.yaml
```

Help me please to figure out what I'm doing wrong.
Thank you!

**Comment by Jakski** [comment]
Hi @spellanser!
Thank you for reporting this issue.
I was able to reproduce this problem, with command:
```
$> sphinx-build -M man source/ _build
```
invoked from catalog `docs/`. `autoyaml_root` was used relatively to current working directory. I changed this behavior to more intuitive. Now `autoyaml_root` is used relatively to catalog, where **conf.py** remains. Can you confirm, that everything is working OK in version [0.4.0](https://pypi.python.org/pypi?:action=display&name=sphinxcontrib-autoyaml&version=0.4.0)? This should build properly:
```
.. autoyaml:: splunk/connection.yaml
```
with `autoyaml_root = "../../"` in **conf.py**.

**Comment by spellancer** [comment]
Now it's building without any error, but nothing seems to be documented.
How I provided docstrings in yaml:

```
### 
# Docstring
###
 ...
### DOCSTRING
````

**Important**: `pip install --upgrade sphinxcontrib-autoyaml` automatically upgraded sphinx to 1.7.0 version. Which is broken for me -- can't build anything. So I have manually downgraded it to Sphinx==1.6.6.

**Comment by Jakski** [comment]
> pip install --upgrade sphinxcontrib-autoyaml automatically upgraded sphinx to 1.7.0

`sphinxcontrib-autoyaml` doesn't enforce specific version of Sphinx. I recommend you to create file with constraints for pip, e.g.:
```
Sphinx==1.6.6
```
and use it while installing dependencies:
```
$> pip install -c constraints.txt sphinxcontrib-autoyaml
```
It will lock Sphinx version.

> Now it's building without any error, but nothing seems to be documented.

I wasn't able to reproduce this issue with following directory structure:
```
.
├── constraints.txt
├── docs
│   ├── _build
│   │   ├── doctrees
│   │   └── man
│   └── source
│       ├── conf.py
│       └── splunk.rst
└── splunk
    └── connection.yaml
```
by issuing command:
```
sphinx-build -M man source/ _build/
```
in `docs/` catalog. `connection.yaml` has the same content like you mentioned in comment earlier. `sphinxcontrib-autoyaml` detected and placed docstrings(_Docstring_, _DOCSTRING_) in documentation. Can you ensure that extension parses your file? Since version [0.4.1](https://pypi.python.org/pypi/sphinxcontrib-autoyaml/0.4.1) extension logs messages like:
```
[autoyaml] parsing file: <path/to/your/yaml/file>
```
in debug level(argument `-vv` passed to `sphinx-build`).

**Comment by spellancer** [comment]
Thank you, I will try with constraints.
