### ISSUE TITLE
Add some example YAML files to README

### ISSUE THREAD

**Issue by johnthagen** [Jakski/sphinxcontrib-autoyaml#3]
It would be helpful if there were some actual YAML examples in the README to demonstrate what an example YAML file should look like, and how that gets converted into Sphinx documentation.

**Comment by Jakski** [comment]
Thank you for feedback. I've included example in README. I also encourage to take a look at tests: https://github.com/Jakski/sphinxcontrib-autoyaml/tree/4d8113af77978c54d38092d48fa808cf3e7330ba/tests/examples/output
They cover most use cases.

**Comment by johnthagen** [comment]
Looks great! Closing issue as completed.
