### ISSUE TITLE
pip can not fetch the 0.6.0 version, just the old 0.5.0

### ISSUE THREAD

**Issue by Thorsten-Sick** [Jakski/sphinxcontrib-autoyaml#6]
Hi

According to 
https://pypi.org/project/sphinxcontrib-autoyaml/0.6.0/
the 0.6.0 version is released. But my pip can only see the 0.5.0

pip3 install -U sphinxcontrib-autoyaml
Requirement already satisfied: sphinxcontrib-autoyaml in ./venv/lib/python3.8/site-packages (0.5.0)

Is there something wrong with pypi or is it just my setup ?

Thanks

**Comment by Jakski** [comment]
Version 0.6.0 required Python >= 3.9, < 4. I've re-run tests with older Python to ensure that compatibility is retained. [0.6.1](https://pypi.org/project/sphinxcontrib-autoyaml/0.6.1/) will be now detected correctly by pip with Python 3.8 and you should be able to install it.
