### ISSUE TITLE
PyPI version and repo version

### ISSUE THREAD

**Issue by kakila** [Jakski/sphinxcontrib-autoyaml#8]
Hi,

The PyPI version of this package https://pypi.org/project/sphinxcontrib-yaml/ is higher than in the repo, but the release date of the PyPI version is way older than the latests commits to the repo.

From where should I install to make sure I have the latest version of the code?

**Comment by Jakski** [comment]
![obsolete-yaml](https://user-images.githubusercontent.com/8525083/143680440-a676b6fd-9e16-4510-b80f-22368d966814.png)
`sphinxcontrib-yaml` package is obsolete. See https://pypi.org/project/sphinxcontrib-autoyaml/ instead. It contains the latest code.
